/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __cars_driving_control_cmd_t_hpp__
#define __cars_driving_control_cmd_t_hpp__


namespace cars
{

class driving_control_cmd_t
{
    public:
        int64_t    utime;
        int8_t     type;
        double     steering_angle;
        double     throttle_value;
        double     brake_value;

    public:
        static const int8_t   TYPE_START_CAR = 0;
        static const int8_t   TYPE_GEAR_FORWARD = 1;
        static const int8_t   TYPE_GEAR_NEUTRAL = 2;
        static const int8_t   TYPE_GEAR_REVERSE = 3;
        static const int8_t   TYPE_DRIVE = 4;
        static const int8_t   TYPE_BRAKE = 5;
        static const int8_t   TYPE_E_STOP = 6;
        static const int8_t   TYPE_SWITCH_OFF_ENGINE = 7;
        static const int8_t   TYPE_DRIVE_DELTA_STEERING = 8;
        static const int8_t   TYPE_DRIVE_DELTA_THROTTLE = 9;
        static const int8_t   TYPE_HANDBRAKE_ON = 10;
        static const int8_t   TYPE_HANDBRAKE_OFF = 11;
        static const int8_t   TYPE_START_SEQUENCE = 12;

    public:
        inline int encode(void *buf, int offset, int maxlen) const;
        inline int getEncodedSize() const;
        inline int decode(const void *buf, int offset, int maxlen);
        inline static int64_t getHash();
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int driving_control_cmd_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int driving_control_cmd_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int driving_control_cmd_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t driving_control_cmd_t::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* driving_control_cmd_t::getTypeName()
{
    return "driving_control_cmd_t";
}

int driving_control_cmd_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->utime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->type, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->steering_angle, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->throttle_value, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->brake_value, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int driving_control_cmd_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->utime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->type, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->steering_angle, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->throttle_value, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->brake_value, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int driving_control_cmd_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    return enc_size;
}

int64_t driving_control_cmd_t::_computeHash(const __lcm_hash_ptr *)
{
    int64_t hash = 0x4c740f35351b7e29LL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
