"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class lcmt_driving_control_cmd_t(object):
    __slots__ = ["timestamp", "steering_angle", "throttle_value", "brake_value"]

    def __init__(self):
        self.timestamp = 0
        self.steering_angle = 0.0
        self.throttle_value = 0.0
        self.brake_value = 0.0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(lcmt_driving_control_cmd_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qddd", self.timestamp, self.steering_angle, self.throttle_value, self.brake_value))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != lcmt_driving_control_cmd_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_driving_control_cmd_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_driving_control_cmd_t()
        self.timestamp, self.steering_angle, self.throttle_value, self.brake_value = struct.unpack(">qddd", buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lcmt_driving_control_cmd_t in parents: return 0
        tmphash = (0x7b56b5bb197a650) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_driving_control_cmd_t._packed_fingerprint is None:
            lcmt_driving_control_cmd_t._packed_fingerprint = struct.pack(">Q", lcmt_driving_control_cmd_t._get_hash_recursive([]))
        return lcmt_driving_control_cmd_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

